import { Hotel } from "@/core/entities/Hotel";
import { Room } from "@/core/entities/Room";
import { Booking } from "@/core/entities/Booking";
import { RoomType } from "@/core/enums/RoomType";
import { BookingStatus } from "@/core/enums/BookingStatus";

export const MOCK_HOTELS: Hotel[] = [
    {
        id: "h1",
        name: "Le Grand Palais",
        description: "Hôtel de luxe au cœur de Paris, à deux pas des Champs-Élysées.",
        address: "10 Avenue des Champs-Élysées",
        city: "Paris",
        country: "France",
        latitude: 48.8698, longitude: 2.3079,
        stars: 5, rating: 4.8, reviewCount: 1284,
        images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
        amenities: ["WiFi", "Piscine", "Spa", "Restaurant", "Bar", "Parking"],
        priceFrom: 350, currency: "EUR",
    },
    {
        id: "h2",
        name: "Hôtel Riviera Nice",
        description: "Face à la Méditerranée, vue imprenable sur la Promenade des Anglais.",
        address: "45 Promenade des Anglais",
        city: "Nice",
        country: "France",
        latitude: 43.6957, longitude: 7.2659,
        stars: 4, rating: 4.5, reviewCount: 876,
        images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
        amenities: ["WiFi", "Piscine", "Vue mer", "Restaurant", "Plage privée"],
        priceFrom: 180, currency: "EUR",
    },
    {
        id: "h3",
        name: "Château Bordeaux",
        description: "Château du XVIIIe siècle transformé en hôtel de charme au cœur du vignoble.",
        address: "Route des Châteaux",
        city: "Bordeaux",
        country: "France",
        latitude: 44.8378, longitude: -0.5792,
        stars: 4, rating: 4.6, reviewCount: 432,
        images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"],
        amenities: ["WiFi", "Cave à vins", "Restaurant", "Jardins", "Parking"],
        priceFrom: 220, currency: "EUR",
    },
    {
        id: "h4",
        name: "Le Marais Boutique",
        description: "Hôtel boutique design dans un hôtel particulier du Marais.",
        address: "12 Rue de Bretagne",
        city: "Paris",
        country: "France",
        latitude: 48.8637, longitude: 2.3622,
        stars: 4, rating: 4.7, reviewCount: 654,
        images: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800"],
        amenities: ["WiFi", "Bar", "Conciergerie", "Climatisation"],
        priceFrom: 195, currency: "EUR",
    },
    {
        id: "h5",
        name: "Alpes Summit Lodge",
        description: "Au pied des pistes de Chamonix, spa et vue sur le Mont-Blanc.",
        address: "3 Rue du Mont-Blanc",
        city: "Chamonix",
        country: "France",
        latitude: 45.9237, longitude: 6.8694,
        stars: 4, rating: 4.9, reviewCount: 389,
        images: ["https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800"],
        amenities: ["WiFi", "Spa", "Sauna", "Restaurant", "Parking"],
        priceFrom: 280, currency: "EUR",
    },
    {
        id: "h6",
        name: "Villa Provençale",
        description: "Villa luxueuse entourée de lavandes, piscine chauffée et cuisine provençale.",
        address: "Route de Gordes",
        city: "Aix-en-Provence",
        country: "France",
        latitude: 43.5297, longitude: 5.4474,
        stars: 5, rating: 4.7, reviewCount: 298,
        images: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800"],
        amenities: ["WiFi", "Piscine", "Jardins", "Restaurant", "Spa"],
        priceFrom: 310, currency: "EUR",
    },
];

export const MOCK_ROOMS: Room[] = [
    {
        id: "r1", hotelId: "h1", type: RoomType.DOUBLE,
        name: "Chambre Classique",
        description: "Chambre élégante avec vue sur cour intérieure, mobilier Empire.",
        pricePerNight: 350, currency: "EUR",
        capacity: 2, size: 32,
        images: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800"],
        amenities: ["WiFi", "Climatisation", "Minibar", "TV 4K"],
        isAvailable: true, bedCount: 1, bedType: "Grand lit double",
    },
    {
        id: "r2", hotelId: "h1", type: RoomType.DELUXE,
        name: "Chambre Deluxe Vue Ville",
        description: "Spacieuse chambre avec vue panoramique sur Paris.",
        pricePerNight: 520, currency: "EUR",
        capacity: 2, size: 45,
        images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800"],
        amenities: ["WiFi", "Climatisation", "Minibar", "Baignoire", "TV 4K"],
        isAvailable: true, bedCount: 1, bedType: "King size",
    },
    {
        id: "r3", hotelId: "h1", type: RoomType.SUITE,
        name: "Suite Présidentielle",
        description: "Salon séparé, terrasse privée avec vue sur les toits de Paris.",
        pricePerNight: 1200, currency: "EUR",
        capacity: 4, size: 120,
        images: ["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800"],
        amenities: ["WiFi", "Jacuzzi", "Terrasse", "Butler", "TV 4K"],
        isAvailable: false, bedCount: 2, bedType: "2 King size",
    },
    {
        id: "r4", hotelId: "h2", type: RoomType.DOUBLE,
        name: "Chambre Vue Mer",
        description: "Balcon et vue imprenable sur la Méditerranée.",
        pricePerNight: 210, currency: "EUR",
        capacity: 2, size: 28,
        images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
        amenities: ["WiFi", "Climatisation", "Balcon", "TV"],
        isAvailable: true, bedCount: 1, bedType: "Grand lit double",
    },
    {
        id: "r5", hotelId: "h2", type: RoomType.SUITE,
        name: "Suite Méditerranée",
        description: "Terrasse privée, jacuzzi extérieur, panorama 180° sur la mer.",
        pricePerNight: 480, currency: "EUR",
        capacity: 3, size: 75,
        images: ["https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"],
        amenities: ["WiFi", "Jacuzzi", "Terrasse", "TV 4K", "Salon"],
        isAvailable: true, bedCount: 1, bedType: "King size",
    },
    {
        id: "r6", hotelId: "h5", type: RoomType.TWIN,
        name: "Chambre Alpine Twin",
        description: "Chambre en bois de mélèze avec vue sur les sommets.",
        pricePerNight: 290, currency: "EUR",
        capacity: 2, size: 30,
        images: ["https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800"],
        amenities: ["WiFi", "Chauffage", "TV"],
        isAvailable: true, bedCount: 2, bedType: "2 lits simples",
    },
    {
        id: "r7", hotelId: "h5", type: RoomType.FAMILY,
        name: "Suite Familiale Mont-Blanc",
        description: "Vue directe sur le Mont-Blanc, salon et chambre séparée.",
        pricePerNight: 520, currency: "EUR",
        capacity: 5, size: 85,
        images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800"],
        amenities: ["WiFi", "Chauffage", "TV", "Salon", "Kitchenette"],
        isAvailable: true, bedCount: 3, bedType: "1 King + 2 simples",
    },
];

export const MOCK_BOOKINGS: Booking[] = [
    {
        id: "b1", userId: "u1", hotelId: "h1", roomId: "r1",
        hotelName: "Le Grand Palais", roomName: "Chambre Classique",
        checkIn: new Date("2025-06-15"), checkOut: new Date("2025-06-18"),
        guestCount: 2, status: BookingStatus.CONFIRMED,
        totalPrice: 1155, currency: "EUR",
        guestInfo: { firstName: "Marie", lastName: "Dupont", email: "marie@email.com", phone: "+33 6 12 34 56 78" },
        createdAt: new Date("2025-05-01"),
    },
    {
        id: "b2", userId: "u1", hotelId: "h2", roomId: "r4",
        hotelName: "Hôtel Riviera Nice", roomName: "Chambre Vue Mer",
        checkIn: new Date("2025-08-01"), checkOut: new Date("2025-08-07"),
        guestCount: 2, status: BookingStatus.PENDING,
        totalPrice: 1386, currency: "EUR",
        guestInfo: { firstName: "Marie", lastName: "Dupont", email: "marie@email.com", phone: "+33 6 12 34 56 78" },
        createdAt: new Date("2025-05-10"),
    },
];