name: Node CI Booking

on:
  push:
    branches: [ cibooking ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: cd booking && npm install
      - run: cd booking && npm run build