name: Node CI Booking

on:
  push:
    branches: [ cibooking ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: booking

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: cd booking && npm install

      - name: Lancer les tests
        run: npm test

      - name: Build application
        run: npm run build